import React, { useState, useCallback } from 'react';
import Terminal from './components/Terminal';
import BrowserMockup from './components/BrowserMockup';
import CodeDiffViewer from './components/CodeDiffViewer';
import { analyzeUiScreenshot, generateCodeFix } from './services/geminiService';
import { AppState, LogEntry, DetectedIssue, CodeFix } from './types';
import { GoogleGenAI } from '@google/genai';

// Placeholder image for demo purposes
const DEMO_IMAGE = "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1000&auto=format&fit=crop"; 

const App: React.FC = () => {
  // State
  const [appState, setAppState] = useState<AppState>(AppState.IDLE);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [url, setUrl] = useState('');
  const [repo, setRepo] = useState('');
  const [screenshot, setScreenshot] = useState<string | null>(null);
  const [issues, setIssues] = useState<DetectedIssue[]>([]);
  const [currentFix, setCurrentFix] = useState<CodeFix | null>(null);
  const [selectedIssueId, setSelectedIssueId] = useState<string | null>(null);

  // Helper to add logs
  const addLog = useCallback((message: string, type: LogEntry['type'] = 'info') => {
    setLogs(prev => [...prev, {
      id: Math.random().toString(36).substr(2, 9),
      timestamp: new Date(),
      message,
      type
    }]);
  }, []);

  // 1. Initial Scan / Image Upload
  const handleUrlSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!url || !repo) {
        addLog("Please provide both Repo and Deployment URL", "error");
        return;
    }
    setAppState(AppState.SCANNING);
    addLog(`Initiating connection to ${url}...`, "action");
    addLog(`Cloning repository ${repo} (simulated)...`, "info");
    
    // Simulate navigation delay
    setTimeout(() => {
        addLog("Navigation successful. Waiting for DOM idle...", "success");
        // In a real app, we'd screenshot here. For demo, we use a placeholder or prompt.
        addLog("Ready for visual capture.", "info");
    }, 1500);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setScreenshot(reader.result as string);
        addLog("Screenshot captured from manual upload.", "success");
        setAppState(AppState.SCANNING); // Move to scanning visual
        setTimeout(() => startAnalysis(reader.result as string), 1000);
      };
      reader.readAsDataURL(file);
    }
  };

  const loadDemo = () => {
    setUrl('https://vibe-fix-demo.netlify.app');
    setRepo('github.com/demo/vibe-fix');
    setScreenshot(DEMO_IMAGE); // Use a generic messy UI image or Unsplash
    addLog("Loading demo environment...", "action");
    setAppState(AppState.SCANNING);
    setTimeout(() => {
        addLog("Demo loaded.", "success");
        startAnalysis(DEMO_IMAGE);
    }, 1000);
  };

  // 2. Analysis Phase
  const startAnalysis = async (imgData: string) => {
    setAppState(AppState.ANALYZING);
    addLog("Starting Visual AI Analysis (Gemini 2.5 Vision)...", "action");
    
    try {
      const detectedIssues = await analyzeUiScreenshot(imgData);
      setIssues(detectedIssues);
      
      addLog(`Analysis complete. Found ${detectedIssues.length} issues.`, "success");
      detectedIssues.forEach(issue => {
        addLog(`[${issue.severity.toUpperCase()}] ${issue.title} - ${issue.location}`, "info");
      });
      setAppState(AppState.REVIEWING);
    } catch (error) {
      addLog("Failed to analyze screenshot. Check API Key.", "error");
      setAppState(AppState.IDLE);
    }
  };

  // 3. Fix Generation Phase
  const handleFixIssue = async (issue: DetectedIssue) => {
    setSelectedIssueId(issue.id);
    setAppState(AppState.FIXING);
    addLog(`Attempting to heal issue: ${issue.title}`, "action");
    addLog(`Locating component in codebase: ${issue.location}...`, "info");

    try {
        const fix = await generateCodeFix(issue);
        setCurrentFix(fix);
        addLog("Code fix generated by Gemini 3 Flash.", "success");
    } catch (error) {
        addLog("Failed to generate code fix.", "error");
        setAppState(AppState.REVIEWING);
    }
  };

  // 4. Verification Phase
  const handleApplyFix = () => {
    if (!currentFix) return;
    
    setAppState(AppState.VERIFYING);
    setCurrentFix(null);
    addLog("Applying patch...", "action");
    addLog("Running regression tests...", "info");
    
    setTimeout(() => {
        addLog("Fix verified visually. Issue resolved.", "success");
        setIssues(prev => prev.filter(i => i.id !== selectedIssueId));
        setAppState(AppState.REVIEWING);
        if (issues.length <= 1) {
            addLog("All detected issues resolved. Repository is healthy.", "success");
            setAppState(AppState.COMPLETE);
        }
    }, 3000);
  };

  return (
    <div className="flex h-screen w-full bg-background text-white overflow-hidden">
      {/* Sidebar: Controls & Terminal */}
      <div className="w-1/3 min-w-[400px] border-r border-surfaceHighlight flex flex-col bg-[#0f0f0f]">
        {/* Header */}
        <div className="p-6 border-b border-surfaceHighlight">
          <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-secondary mb-2">
            VibeFix
          </h1>
          <p className="text-gray-400 text-sm">Autonomous UI Healer Agent</p>
        </div>

        {/* Inputs */}
        <div className="p-6 space-y-4 border-b border-surfaceHighlight">
            {appState === AppState.IDLE ? (
                 <>
                    <input 
                        type="text" 
                        placeholder="GitHub Repo URL"
                        className="w-full bg-surfaceHighlight border border-white/10 rounded px-4 py-2 text-sm focus:outline-none focus:border-primary transition"
                        value={repo}
                        onChange={(e) => setRepo(e.target.value)}
                    />
                    <input 
                        type="text" 
                        placeholder="Deployment URL"
                        className="w-full bg-surfaceHighlight border border-white/10 rounded px-4 py-2 text-sm focus:outline-none focus:border-primary transition"
                        value={url}
                        onChange={(e) => setUrl(e.target.value)}
                    />
                    
                    <div className="flex gap-2">
                         <button 
                            onClick={handleUrlSubmit}
                            className="flex-1 bg-white text-black font-semibold py-2 rounded hover:bg-gray-200 transition text-sm"
                        >
                            Start Agent
                        </button>
                        <button 
                            onClick={loadDemo}
                            className="px-4 py-2 border border-white/20 rounded hover:bg-white/5 transition text-sm"
                        >
                            Demo
                        </button>
                    </div>

                    <div className="relative">
                        <div className="absolute inset-0 flex items-center">
                            <span className="w-full border-t border-white/10" />
                        </div>
                        <div className="relative flex justify-center text-xs uppercase">
                            <span className="bg-[#0f0f0f] px-2 text-gray-500">Or Upload Screenshot</span>
                        </div>
                    </div>
                     <input 
                        type="file" 
                        accept="image/*"
                        onChange={handleFileUpload}
                        className="w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-primary file:text-white hover:file:bg-violet-600 transition"
                    />
                </>
            ) : (
                <div className="space-y-2">
                    <div className="flex justify-between items-center">
                        <span className="text-xs font-mono text-gray-500">STATUS</span>
                        <span className={`text-xs font-bold px-2 py-1 rounded ${
                            appState === AppState.COMPLETE ? 'bg-green-500/20 text-green-400' : 'bg-primary/20 text-primary'
                        }`}>
                            {appState}
                        </span>
                    </div>
                    {selectedIssueId && appState !== AppState.COMPLETE && (
                         <div className="flex justify-between items-center">
                            <span className="text-xs font-mono text-gray-500">CURRENT TASK</span>
                            <span className="text-xs text-white truncate max-w-[200px]">Fixing {selectedIssueId}</span>
                        </div>
                    )}
                </div>
            )}
        </div>

        {/* Issue List */}
        {issues.length > 0 && appState !== AppState.SCANNING && appState !== AppState.ANALYZING && (
            <div className="flex-1 overflow-y-auto p-4 space-y-3 min-h-0 border-b border-surfaceHighlight scrollbar-hide">
                <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">Detected Anomalies</h3>
                {issues.map(issue => (
                    <div 
                        key={issue.id}
                        onClick={() => appState === AppState.REVIEWING && handleFixIssue(issue)}
                        className={`p-3 rounded border transition cursor-pointer group ${
                            selectedIssueId === issue.id 
                            ? 'bg-primary/10 border-primary' 
                            : 'bg-surfaceHighlight border-transparent hover:border-white/20'
                        }`}
                    >
                        <div className="flex justify-between items-start mb-1">
                            <span className="font-semibold text-sm text-white group-hover:text-primary transition">{issue.title}</span>
                            <span className={`text-[10px] px-1.5 py-0.5 rounded font-mono ${
                                issue.severity === 'high' ? 'bg-red-500/20 text-red-400' : 
                                issue.severity === 'medium' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-blue-500/20 text-blue-400'
                            }`}>
                                {issue.severity}
                            </span>
                        </div>
                        <p className="text-xs text-gray-400 line-clamp-2">{issue.description}</p>
                        {appState === AppState.REVIEWING && (
                            <div className="mt-2 text-right">
                                <span className="text-[10px] text-primary opacity-0 group-hover:opacity-100 transition">Click to Heal →</span>
                            </div>
                        )}
                    </div>
                ))}
            </div>
        )}

        {/* Terminal */}
        <div className="h-1/3 min-h-[200px] p-4 bg-[#0a0a0a]">
            <Terminal logs={logs} />
        </div>
      </div>

      {/* Main Area: Browser / Visualization */}
      <div className="flex-1 p-8 bg-[#050505] flex items-center justify-center relative">
         <div className="absolute top-0 left-0 w-full h-full overflow-hidden opacity-20 pointer-events-none">
            <div className="absolute w-[500px] h-[500px] bg-primary/20 blur-[100px] rounded-full -top-20 -left-20"></div>
            <div className="absolute w-[400px] h-[400px] bg-secondary/10 blur-[100px] rounded-full bottom-0 right-0"></div>
         </div>

         {/* Visual Container */}
         <div className="w-full max-w-5xl h-[85%] relative z-10 flex flex-col items-center">
            
            {appState === AppState.FIXING && currentFix ? (
                <CodeDiffViewer 
                    fix={currentFix} 
                    onApply={handleApplyFix}
                    onDiscard={() => {
                        setCurrentFix(null);
                        setAppState(AppState.REVIEWING);
                        addLog("Fix discarded by user.", "info");
                    }}
                />
            ) : (
                <BrowserMockup 
                    url={url || 'http://localhost:3000'} 
                    imageSrc={screenshot}
                    isScanning={appState === AppState.SCANNING || appState === AppState.ANALYZING}
                >
                    {/* Overlay markers for issues */}
                    {(appState === AppState.REVIEWING || appState === AppState.FIXING) && issues.map((issue, idx) => (
                        <div 
                            key={issue.id}
                            className="absolute w-8 h-8 flex items-center justify-center rounded-full bg-red-500/80 text-white font-bold text-xs shadow-lg animate-bounce cursor-pointer hover:scale-110 transition z-30"
                            style={{ 
                                top: `${20 + (idx * 15)}%`, // Randomized for demo simplicity since we don't have real bounding boxes
                                left: `${30 + (idx * 10)}%` 
                            }}
                            title={issue.title}
                            onClick={() => handleFixIssue(issue)}
                        >
                            {idx + 1}
                        </div>
                    ))}
                </BrowserMockup>
            )}

            {appState === AppState.COMPLETE && (
                <div className="absolute inset-0 bg-black/80 flex flex-col items-center justify-center rounded-lg backdrop-blur-sm z-50">
                    <div className="text-6xl mb-4">✨</div>
                    <h2 className="text-3xl font-bold text-white mb-2">All Clear!</h2>
                    <p className="text-gray-400 mb-6">VibeFix has healed the detected UI anomalies.</p>
                    <button 
                        onClick={() => window.location.reload()}
                        className="px-6 py-3 bg-white text-black font-bold rounded hover:bg-gray-200 transition"
                    >
                        Start New Session
                    </button>
                </div>
            )}
         </div>
      </div>
    </div>
  );
};

export default App;
